ebs-hal-uc-stm32: hal_platform/f4xx/exti_handlers.c File Reference
exti_handlers.c File Reference
#include "stm32f4xx_hal.h"
#include <application.h>
#include <irq_handlers.h>
#include <platform/debug.h>
#include <hal/uc/gpio.h>
#include "exti_handlers.h"
Functions
static void exti_handler (uint8_t exti_line)
void EXTI0_IRQHandler (void)
This function handles EXTI line0 interrupt.
void EXTI1_IRQHandler (void)
This function handles EXTI line1 interrupt.
void EXTI2_IRQHandler (void)
This function handles EXTI line2 interrupt.
void EXTI3_IRQHandler (void)
This function handles EXTI line3 interrupt.
void EXTI4_IRQHandler (void)
This function handles EXTI line4 interrupts.
void EXTI9_5_IRQHandler (void)
This function handles EXTI line 5-9 interrupts.
void EXTI15_10_IRQHandler (void)
This function handles EXTI line 10-15 interrupts.
Variables
volatile uint8_t __exti_handler_inclusion
void(* exti_gpio_handlers [MAX_EXTI_GPIO_LINES])(uint8_t) = {0}
Function Documentation
EXTI0_IRQHandler()
void EXTI0_IRQHandler (void)
This function handles EXTI line0 interrupt.
Definition at line 22 of file exti_handlers.c.
References exti_handler().
EXTI15_10_IRQHandler()
void EXTI15_10_IRQHandler (void)
This function handles EXTI line 10-15 interrupts.
Definition at line 91 of file exti_handlers.c.
References exti_handler().
EXTI1_IRQHandler()
void EXTI1_IRQHandler (void)
This function handles EXTI line1 interrupt.
Definition at line 33 of file exti_handlers.c.
References exti_handler().
EXTI2_IRQHandler()
void EXTI2_IRQHandler (void)
This function handles EXTI line2 interrupt.
Definition at line 44 of file exti_handlers.c.
References exti_handler().
EXTI3_IRQHandler()
void EXTI3_IRQHandler (void)
This function handles EXTI line3 interrupt.
Definition at line 55 of file exti_handlers.c.
References exti_handler().
EXTI4_IRQHandler()
void EXTI4_IRQHandler (void)
This function handles EXTI line4 interrupts.
Definition at line 66 of file exti_handlers.c.
References exti_handler().
EXTI9_5_IRQHandler()
void EXTI9_5_IRQHandler (void)
This function handles EXTI line 5-9 interrupts.
Definition at line 77 of file exti_handlers.c.
References exti_handler().
exti_handler()
static void exti_handler (uint8_t exti_line) inline static
Definition at line 13 of file exti_handlers.c.
References exti_gpio_handlers.
Referenced by EXTI0_1_IRQHandler(), EXTI0_IRQHandler(), EXTI10_IRQHandler(), EXTI11_IRQHandler(), EXTI12_IRQHandler(), EXTI13_IRQHandler(), EXTI14_IRQHandler(), EXTI15_10_IRQHandler(), EXTI15_IRQHandler(), EXTI1_IRQHandler(), EXTI2_3_IRQHandler(), EXTI2_IRQHandler(), EXTI3_IRQHandler(), EXTI4_15_IRQHandler(), EXTI4_IRQHandler(), EXTI5_IRQHandler(), EXTI6_IRQHandler(), EXTI7_IRQHandler(), EXTI8_IRQHandler(), EXTI9_5_IRQHandler(), and EXTI9_IRQHandler().
Variable Documentation
__exti_handler_inclusion
volatile uint8_t __exti_handler_inclusion
Definition at line 10 of file exti_handlers.c.
exti_gpio_handlers
void(* exti_gpio_handlers[MAX_EXTI_GPIO_LINES])(uint8_t) (uint8_t) = {0}
Definition at line 11 of file exti_handlers.c.
Referenced by exti_handler().