ebs-hal-uc-stm32: hal_platform/h7rsxx/exti_handlers.c File Reference
exti_handlers.c File Reference
#include "stm32h7rsxx_hal.h"
#include <application.h>
#include <irq_handlers.h>
#include <platform/debug.h>
#include <hal/uc/gpio.h>
#include "exti_handlers.h"
#include <platform/sections.h>
Functions
FASTEXEC void EXTI0_IRQHandler (void)
FASTEXEC void EXTI1_IRQHandler (void)
FASTEXEC void EXTI2_IRQHandler (void)
FASTEXEC void EXTI3_IRQHandler (void)
FASTEXEC void EXTI4_IRQHandler (void)
FASTEXEC void EXTI5_IRQHandler (void)
FASTEXEC void EXTI6_IRQHandler (void)
FASTEXEC void EXTI7_IRQHandler (void)
FASTEXEC void EXTI8_IRQHandler (void)
FASTEXEC void EXTI9_IRQHandler (void)
FASTEXEC void EXTI10_IRQHandler (void)
FASTEXEC void EXTI11_IRQHandler (void)
FASTEXEC void EXTI12_IRQHandler (void)
FASTEXEC void EXTI13_IRQHandler (void)
FASTEXEC void EXTI14_IRQHandler (void)
FASTEXEC void EXTI15_IRQHandler (void)
Variables
volatile uint8_t __exti_handler_inclusion
void(* exti_gpio_handlers [MAX_EXTI_GPIO_LINES])(uint8_t)
Function Documentation
EXTI0_IRQHandler()
FASTEXEC void EXTI0_IRQHandler (void)
Definition at line 27 of file exti_handlers.c.
References exti_handler().
EXTI10_IRQHandler()
FASTEXEC void EXTI10_IRQHandler (void)
Definition at line 87 of file exti_handlers.c.
References exti_handler().
EXTI11_IRQHandler()
FASTEXEC void EXTI11_IRQHandler (void)
Definition at line 93 of file exti_handlers.c.
References exti_handler().
EXTI12_IRQHandler()
FASTEXEC void EXTI12_IRQHandler (void)
Definition at line 99 of file exti_handlers.c.
References exti_handler().
EXTI13_IRQHandler()
FASTEXEC void EXTI13_IRQHandler (void)
Definition at line 105 of file exti_handlers.c.
References exti_handler().
EXTI14_IRQHandler()
FASTEXEC void EXTI14_IRQHandler (void)
Definition at line 111 of file exti_handlers.c.
References exti_handler().
EXTI15_IRQHandler()
FASTEXEC void EXTI15_IRQHandler (void)
Definition at line 117 of file exti_handlers.c.
References exti_handler().
EXTI1_IRQHandler()
FASTEXEC void EXTI1_IRQHandler (void)
Definition at line 33 of file exti_handlers.c.
References exti_handler().
EXTI2_IRQHandler()
FASTEXEC void EXTI2_IRQHandler (void)
Definition at line 39 of file exti_handlers.c.
References exti_handler().
EXTI3_IRQHandler()
FASTEXEC void EXTI3_IRQHandler (void)
Definition at line 45 of file exti_handlers.c.
References exti_handler().
EXTI4_IRQHandler()
FASTEXEC void EXTI4_IRQHandler (void)
Definition at line 51 of file exti_handlers.c.
References exti_handler().
EXTI5_IRQHandler()
FASTEXEC void EXTI5_IRQHandler (void)
Definition at line 57 of file exti_handlers.c.
References exti_handler().
EXTI6_IRQHandler()
FASTEXEC void EXTI6_IRQHandler (void)
Definition at line 63 of file exti_handlers.c.
References exti_handler().
EXTI7_IRQHandler()
FASTEXEC void EXTI7_IRQHandler (void)
Definition at line 69 of file exti_handlers.c.
References exti_handler().
EXTI8_IRQHandler()
FASTEXEC void EXTI8_IRQHandler (void)
Definition at line 75 of file exti_handlers.c.
References exti_handler().
EXTI9_IRQHandler()
FASTEXEC void EXTI9_IRQHandler (void)
Definition at line 81 of file exti_handlers.c.
References exti_handler().
Variable Documentation
__exti_handler_inclusion
volatile uint8_t __exti_handler_inclusion
Definition at line 12 of file exti_handlers.c.
exti_gpio_handlers
void(* exti_gpio_handlers[MAX_EXTI_GPIO_LINES])(uint8_t) (uint8_t)
Definition at line 13 of file exti_handlers.c.