ebs-hal-uc-stm32: hal_platform/u0xx/uart_handlers.c File Reference
uart_handlers.c File Reference
#include <application.h>
#include <irq_handlers.h>
#include <hal/uc/uart.h>
#include "uart_handlers.h"
Functions
static void _uart_handler_tx_norm (const HAL_BASE_t intfnum)
static void _uart_handler_rx_norm (const HAL_BASE_t intfnum)
static void _uart_handler_tx_fifo (const HAL_BASE_t intfnum)
static void _uart_handler_rx_fifo (const HAL_BASE_t intfnum)
static void _uart_handler_norm (const HAL_BASE_t intfnum)
static void _uart_handler_fifo (const HAL_BASE_t intfnum)
void USART1_IRQHandler (void)
void USART2_LPUART2_IRQHandler (void)
void USART3_LPUART1_IRQHandler (void)
void USART4_LPUART3_IRQHandler (void)
Variables
volatile uint8_t __uart_handler_inclusion
Function Documentation
_uart_handler_fifo()
static void _uart_handler_fifo (const HAL_BASE_t intfnum) inline static
Definition at line 95 of file uart_handlers.c.
References _uart_handler_rx_fifo(), and _uart_handler_tx_fifo().
Referenced by USART1_IRQHandler(), USART2_LPUART2_IRQHandler(), USART3_LPUART1_IRQHandler(), and USART4_LPUART3_IRQHandler().
_uart_handler_norm()
static void _uart_handler_norm (const HAL_BASE_t intfnum) inline static
Definition at line 85 of file uart_handlers.c.
References _uart_handler_rx_norm(), and _uart_handler_tx_norm().
Referenced by USART1_IRQHandler(), USART2_LPUART2_IRQHandler(), USART3_LPUART1_IRQHandler(), and USART4_LPUART3_IRQHandler().
_uart_handler_rx_fifo()
static void _uart_handler_rx_fifo (const HAL_BASE_t intfnum) inline static
Definition at line 58 of file uart_handlers.c.
Referenced by _uart_handler_fifo().
_uart_handler_rx_norm()
static void _uart_handler_rx_norm (const HAL_BASE_t intfnum) inline static
Definition at line 31 of file uart_handlers.c.
Referenced by _uart_handler_norm().
_uart_handler_tx_fifo()
static void _uart_handler_tx_fifo (const HAL_BASE_t intfnum) inline static
Definition at line 43 of file uart_handlers.c.
Referenced by _uart_handler_fifo().
_uart_handler_tx_norm()
static void _uart_handler_tx_norm (const HAL_BASE_t intfnum) inline static
Definition at line 19 of file uart_handlers.c.
Referenced by _uart_handler_norm().
USART1_IRQHandler()
void USART1_IRQHandler (void)
Definition at line 106 of file uart_handlers.c.
References _uart_handler_fifo(), and _uart_handler_norm().
USART2_LPUART2_IRQHandler()
void USART2_LPUART2_IRQHandler (void)
Definition at line 116 of file uart_handlers.c.
References _uart_handler_fifo(), and _uart_handler_norm().
USART3_LPUART1_IRQHandler()
void USART3_LPUART1_IRQHandler (void)
Definition at line 134 of file uart_handlers.c.
References _uart_handler_fifo(), and _uart_handler_norm().
USART4_LPUART3_IRQHandler()
void USART4_LPUART3_IRQHandler (void)
Definition at line 151 of file uart_handlers.c.
References _uart_handler_fifo(), and _uart_handler_norm().
Variable Documentation
__uart_handler_inclusion
volatile uint8_t __uart_handler_inclusion
Definition at line 7 of file uart_handlers.c.