#ifndef UART_HANDLERS_H
#define UART_HANDLERS_H

#include <stdint.h>
// Handlers for this platform are generated by CubeMX and declared in 
// include/irq_handlers.h  

extern volatile uint8_t __uart_handler_inclusion;

#endif
