
#define uC_DMA_DEFAULT_PRIORITY         DMA_PRIO_LOW
#define uC_DMA_DEFAULT_ENABLE_CB_TC     EBS_TRUE
#define uC_DMA_DEFAULT_ENABLE_CB_HC     EBS_FALSE
#define uC_DMA_DEFAULT_CHANNEL_TYPE     DMA_CHN_TYPE_LINEAR

#ifndef uC_DMA1_CH0_TYPE
    #define uC_DMA1_CH0_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH1_TYPE
    #define uC_DMA1_CH1_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH2_TYPE
    #define uC_DMA1_CH2_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH3_TYPE
    #define uC_DMA1_CH3_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH4_TYPE
    #define uC_DMA1_CH4_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH5_TYPE
    #define uC_DMA1_CH5_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH6_TYPE
    #define uC_DMA1_CH6_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH7_TYPE
    #define uC_DMA1_CH7_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH8_TYPE
    #define uC_DMA1_CH8_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH9_TYPE
    #define uC_DMA1_CH9_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH10_TYPE
    #define uC_DMA1_CH10_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH11_TYPE
    #define uC_DMA1_CH11_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH12_TYPE
    #define uC_DMA1_CH12_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH13_TYPE
    #define uC_DMA1_CH13_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH14_TYPE
    #define uC_DMA1_CH14_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA1_CH15_TYPE
    #define uC_DMA1_CH15_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif


#ifndef uC_DMA2_CH0_TYPE
    #define uC_DMA2_CH0_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH1_TYPE
    #define uC_DMA2_CH1_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH2_TYPE
    #define uC_DMA2_CH2_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH3_TYPE
    #define uC_DMA2_CH3_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH4_TYPE
    #define uC_DMA2_CH4_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH5_TYPE
    #define uC_DMA2_CH5_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH6_TYPE
    #define uC_DMA2_CH6_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH7_TYPE
    #define uC_DMA2_CH7_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH8_TYPE
    #define uC_DMA2_CH8_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH9_TYPE
    #define uC_DMA2_CH9_TYPE        uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH10_TYPE
    #define uC_DMA2_CH10_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH11_TYPE
    #define uC_DMA2_CH11_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH12_TYPE
    #define uC_DMA2_CH12_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH13_TYPE
    #define uC_DMA2_CH13_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH14_TYPE
    #define uC_DMA2_CH14_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif
#ifndef uC_DMA2_CH15_TYPE
    #define uC_DMA2_CH15_TYPE       uC_DMA_DEFAULT_CHANNEL_TYPE
#endif


#ifndef uC_DMA1_CH0_PRIORITY
    #define uC_DMA1_CH0_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH1_PRIORITY
    #define uC_DMA1_CH1_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH2_PRIORITY
    #define uC_DMA1_CH2_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH3_PRIORITY
    #define uC_DMA1_CH3_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH4_PRIORITY
    #define uC_DMA1_CH4_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH5_PRIORITY
    #define uC_DMA1_CH5_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH6_PRIORITY
    #define uC_DMA1_CH6_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH7_PRIORITY
    #define uC_DMA1_CH7_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH8_PRIORITY
    #define uC_DMA1_CH8_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH9_PRIORITY
    #define uC_DMA1_CH9_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH10_PRIORITY
    #define uC_DMA1_CH11_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH12_PRIORITY
    #define uC_DMA1_CH12_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH13_PRIORITY
    #define uC_DMA1_CH13_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH14_PRIORITY
    #define uC_DMA1_CH14_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA1_CH15_PRIORITY
    #define uC_DMA1_CH15_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif

#ifndef uC_DMA2_CH0_PRIORITY
    #define uC_DMA2_CH0_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH1_PRIORITY
    #define uC_DMA2_CH1_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH2_PRIORITY
    #define uC_DMA2_CH2_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH3_PRIORITY
    #define uC_DMA2_CH3_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH4_PRIORITY
    #define uC_DMA2_CH4_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH5_PRIORITY    
    #define uC_DMA2_CH5_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH6_PRIORITY
    #define uC_DMA2_CH6_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH7_PRIORITY
    #define uC_DMA2_CH7_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH8_PRIORITY
    #define uC_DMA2_CH8_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH9_PRIORITY
    #define uC_DMA2_CH9_PRIORITY    uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH10_PRIORITY
    #define uC_DMA2_CH11_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH12_PRIORITY
    #define uC_DMA2_CH12_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif
    #ifndef uC_DMA2_CH13_PRIORITY
    #define uC_DMA2_CH13_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH14_PRIORITY
    #define uC_DMA2_CH14_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif
#ifndef uC_DMA2_CH15_PRIORITY
    #define uC_DMA2_CH15_PRIORITY   uC_DMA_DEFAULT_PRIORITY
#endif

#ifndef uC_DMA1_CH0_ENABLE_CB_TC
    #define uC_DMA1_CH0_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH1_ENABLE_CB_TC
    #define uC_DMA1_CH1_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH2_ENABLE_CB_TC
    #define uC_DMA1_CH2_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH3_ENABLE_CB_TC
    #define uC_DMA1_CH3_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH4_ENABLE_CB_TC
    #define uC_DMA1_CH4_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH5_ENABLE_CB_TC
    #define uC_DMA1_CH5_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH6_ENABLE_CB_TC
    #define uC_DMA1_CH6_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH7_ENABLE_CB_TC
    #define uC_DMA1_CH7_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH8_ENABLE_CB_TC
    #define uC_DMA1_CH8_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH9_ENABLE_CB_TC
    #define uC_DMA1_CH9_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH10_ENABLE_CB_TC
    #define uC_DMA1_CH10_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH11_ENABLE_CB_TC
    #define uC_DMA1_CH11_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH12_ENABLE_CB_TC
    #define uC_DMA1_CH12_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH13_ENABLE_CB_TC
    #define uC_DMA1_CH13_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH14_ENABLE_CB_TC
    #define uC_DMA1_CH14_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA1_CH15_ENABLE_CB_TC
    #define uC_DMA1_CH15_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif

#ifndef uC_DMA2_CH0_ENABLE_CB_TC
    #define uC_DMA2_CH0_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH1_ENABLE_CB_TC
    #define uC_DMA2_CH1_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH2_ENABLE_CB_TC
    #define uC_DMA2_CH2_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH3_ENABLE_CB_TC
    #define uC_DMA2_CH3_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH4_ENABLE_CB_TC
    #define uC_DMA2_CH4_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH5_ENABLE_CB_TC
    #define uC_DMA2_CH5_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH6_ENABLE_CB_TC
    #define uC_DMA2_CH6_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH7_ENABLE_CB_TC
    #define uC_DMA2_CH7_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH8_ENABLE_CB_TC
    #define uC_DMA2_CH8_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH9_ENABLE_CB_TC
    #define uC_DMA2_CH9_ENABLE_CB_TC     uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH10_ENABLE_CB_TC
    #define uC_DMA2_CH10_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH11_ENABLE_CB_TC
    #define uC_DMA2_CH11_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH12_ENABLE_CB_TC
    #define uC_DMA2_CH12_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH13_ENABLE_CB_TC
    #define uC_DMA2_CH13_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH14_ENABLE_CB_TC
    #define uC_DMA2_CH14_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif
#ifndef uC_DMA2_CH15_ENABLE_CB_TC
    #define uC_DMA2_CH15_ENABLE_CB_TC    uC_DMA_DEFAULT_ENABLE_CB_TC
#endif

#ifndef uC_DMA1_CH0_ENABLE_CB_HC
    #define uC_DMA1_CH0_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH1_ENABLE_CB_HC
    #define uC_DMA1_CH1_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH2_ENABLE_CB_HC
    #define uC_DMA1_CH2_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH3_ENABLE_CB_HC
    #define uC_DMA1_CH3_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH4_ENABLE_CB_HC
    #define uC_DMA1_CH4_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH5_ENABLE_CB_HC
    #define uC_DMA1_CH5_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH6_ENABLE_CB_HC
    #define uC_DMA1_CH6_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH7_ENABLE_CB_HC
    #define uC_DMA1_CH7_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH8_ENABLE_CB_HC
    #define uC_DMA1_CH8_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH9_ENABLE_CB_HC
    #define uC_DMA1_CH9_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH10_ENABLE_CB_HC
    #define uC_DMA1_CH10_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH11_ENABLE_CB_HC
    #define uC_DMA1_CH11_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH12_ENABLE_CB_HC
    #define uC_DMA1_CH12_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH13_ENABLE_CB_HC
    #define uC_DMA1_CH13_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH14_ENABLE_CB_HC
    #define uC_DMA1_CH14_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA1_CH15_ENABLE_CB_HC
    #define uC_DMA1_CH15_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif

#ifndef uC_DMA2_CH0_ENABLE_CB_HC
    #define uC_DMA2_CH0_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH1_ENABLE_CB_HC
    #define uC_DMA2_CH1_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH2_ENABLE_CB_HC
    #define uC_DMA2_CH2_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH3_ENABLE_CB_HC
    #define uC_DMA2_CH3_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH4_ENABLE_CB_HC
    #define uC_DMA2_CH4_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH5_ENABLE_CB_HC
    #define uC_DMA2_CH5_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH6_ENABLE_CB_HC
    #define uC_DMA2_CH6_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH7_ENABLE_CB_HC
    #define uC_DMA2_CH7_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH8_ENABLE_CB_HC
    #define uC_DMA2_CH8_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH9_ENABLE_CB_HC
    #define uC_DMA2_CH9_ENABLE_CB_HC     uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH10_ENABLE_CB_HC
    #define uC_DMA2_CH10_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH11_ENABLE_CB_HC
    #define uC_DMA2_CH11_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH12_ENABLE_CB_HC
    #define uC_DMA2_CH12_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH13_ENABLE_CB_HC
    #define uC_DMA2_CH13_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH14_ENABLE_CB_HC
    #define uC_DMA2_CH14_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
#ifndef uC_DMA2_CH15_ENABLE_CB_HC
    #define uC_DMA2_CH15_ENABLE_CB_HC    uC_DMA_DEFAULT_ENABLE_CB_HC
#endif
