#ifndef TIMER_HANDLERS_H
#define TIMER_HANDLERS_H

#include <stdint.h>
// Handlers for this platform are generated by CubeMX and declared in 
// include/irq_handlers.h  

extern volatile uint8_t __timer_handler_inclusion;

#endif
